# Generated by Django 5.0.1 on 2024-01-28 18:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.TextField(max_length=200)),
                ('sala', models.TextField(max_length=2)),
                ('hours', models.DateTimeField(default=datetime.datetime(2024, 1, 28, 18, 40, 35, 252243, tzinfo=datetime.timezone.utc), verbose_name='date published')),
                ('name_client', models.TextField(max_length=200)),
                ('cpf_client', models.TextField(max_length=200)),
                ('method_payment', models.TextField(max_length=200)),
            ],
        ),
    ]
