# Generated by Django 5.0.1 on 2024-01-28 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduling',
            name='author',
            field=models.TextField(default='SOME STRING', max_length=300),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='duration',
            field=models.TextField(default='1hours', max_length=200),
        ),
        migrations.AddField(
            model_name='scheduling',
            name='saladescricao',
            field=models.TextField(default='hd', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='cpf_client',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='hours',
            field=models.DateTimeField(verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='method_payment',
            field=models.TextField(default='dinner', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='name_client',
            field=models.TextField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='sala',
            field=models.TextField(default='1hours', max_length=2),
        ),
    ]
